version: '3'

services:
  db:
    image: "smol_db_server:latest"
    build:
      context: "./"
      dockerfile: "./Dockerfile"
    container_name: "smol_db_server"
    restart: unless-stopped
    ports:
      - "8222:8222"
    volumes:
      - "./db_data:/data"