[package]
name = "smol_db_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.163"
bson = "2.6.1"
serde_json = "1.0.96"