[package]
name = "smol_db_common"
version = "0.1.11"
edition = "2021"
description = "A common library shared between packages that use smol_db"
license = "GPL-3"
license-file = "LICENSE"
repository = "https://github.com/CoryRobertson/smol_db"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.177", features = ["derive","rc"]}
serde_json = "1.0.104"
chrono = "0.4.26"
