[package]
name = "smol_db_server"
version = "0.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smol_db_common = { path = "../smol_db_common" }
serde = { version = "1.0.163", features = ["derive","rc"]}
serde_json = "1.0.96"
rand = "0.8.5"
ctrlc = "3.3.1"